services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'projeto-final'
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '12345678'
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: